export const ActionTypes = {
    SET_REC_VIDEOS: "SET_REC_VIDEOS",
    SET_SUB_VIDEOS: "SET_SUB_VIDEOS",
    SET_VIDEO: "SET_VIDEO",
    REMOVE_VIDEO: "REMOVE_VIDEO",
    SET_COMMENTS: "SET_COMMENTS",
    REMOVE_COMMENTS: "REMOVE_COMMENTS",
    SET_USER: "SET_USER",
    REMOVE_USER: "REMOVE_USER",
    SET_CURRENT_USER: "SET_CURRENT_USER",
    REMOVE_CURRENT_USER: "REMOVE_CURRENT_USER",
};