# Generated by Django 4.1.2 on 2022-10-21 12:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ban',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(max_length=512)),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='SNUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(max_length=16)),
                ('mail', models.CharField(max_length=32)),
                ('photo', models.ImageField(blank=True, upload_to='uploads/avatars/')),
                ('phone_number', models.CharField(blank=True, max_length=16)),
                ('black_list', models.ManyToManyField(blank=True, to='network.ban')),
                ('likes', models.ManyToManyField(blank=True, to='network.like')),
            ],
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('video', models.FileField(upload_to='uploads/videos')),
                ('heading', models.CharField(max_length=128)),
                ('text', models.TextField(max_length=1024)),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='network.snuser')),
                ('comments', models.ManyToManyField(blank=True, related_name='Comments', to='network.comment')),
                ('likes', models.ManyToManyField(blank=True, to='network.like')),
            ],
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subscribed_to', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Subscribed_to', to='network.snuser')),
                ('subscriber', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Subscriber', to='network.snuser')),
            ],
        ),
        migrations.AddField(
            model_name='snuser',
            name='subscribtions',
            field=models.ManyToManyField(blank=True, to='network.subscription'),
        ),
        migrations.AddField(
            model_name='snuser',
            name='videos',
            field=models.ManyToManyField(blank=True, to='network.video'),
        ),
        migrations.AddField(
            model_name='like',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Post', to='network.video'),
        ),
        migrations.AddField(
            model_name='like',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='User', to='network.snuser'),
        ),
        migrations.AddField(
            model_name='comment',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Users', to='network.snuser'),
        ),
        migrations.AddField(
            model_name='comment',
            name='video',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Video', to='network.video'),
        ),
        migrations.AddField(
            model_name='ban',
            name='banned',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Banned', to='network.snuser'),
        ),
        migrations.AddField(
            model_name='ban',
            name='banned_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Banned_by', to='network.snuser'),
        ),
    ]
