# Generated by Django 4.1.2 on 2022-11-23 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='snuser',
            name='verified',
            field=models.BooleanField(default=False),
        ),
    ]
