# Generated by Django 4.1.2 on 2022-11-09 14:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ('creation_date',)},
        ),
    ]
