# Generated by Django 4.1.2 on 2022-11-09 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network', '0001_initial'),
        ('chat', '0002_alter_message_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='chat_members',
            field=models.ManyToManyField(blank=True, to='network.snuser'),
        ),
    ]
